### ISSUE TITLE
 BadMethodCallException

### ISSUE THREAD

**Issue by bobytza** [kjdion84/laraback#1]
Hi, new to Laravel, I'm getting this erorr when running migrations: BadMethodCallException  : Method Illuminate\Database\Query\Builder::roles does not exist.

**Comment by kjdion84** [comment]
I just did a fresh install following the readme. I could not reproduce your error.

What version of Laravel? Did you follow all of the steps?

**Comment by jazadev** [comment]
Hi, I have the same problem, the details are:

Laravel Framework 5.6.11

app\User.php
use Illuminate\Support\Traits\LarabackUser;
use Illuminate\Support\Traits\Timezone;

protected $fillable = [
        'name', 'email', 'password','timezone',
    ];
--------------------------------------------------------------------

  BadMethodCallException  : Method Illuminate\Database\Query\Builder::roles does not exist.

  at /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php: 2575
    2571|         if (Str::startsWith($method, 'where')) {
    2572|             return $this->dynamicWhere($method, $parameters);
    2573|         }
    2574| 
  > 2575|         throw new BadMethodCallException(sprintf(
    2576|             'Method %s::%s does not exist.', static::class, $method
    2577|         ));
    2578|     }
    2579| }

  Exception trace:

  1   Illuminate\Database\Query\Builder::__call("roles", [])
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php : 1288

  2   Illuminate\Database\Eloquent\Builder::__call("roles", [])
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php : 1504

  3   Illuminate\Database\Eloquent\Model::__call("roles", [])
      /var/www/laradmin/vendor/kjdion84/laraback/database/migrations/2017_12_13_100000_create_permissions_table.php : 32

  4   CreatePermissionsTable::up()
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 359

  5   Illuminate\Database\Migrations\Migrator::Illuminate\Database\Migrations\{closure}()
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 366

  6   Illuminate\Database\Migrations\Migrator::runMigration(Object(CreatePermissionsTable), "up")
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 177

  7   Illuminate\Database\Migrations\Migrator::runUp("/var/www/laradmin/vendor/kjdion84/laraback/src/../database/migrations/2017_12_13_100000_create_permissions_table.php")
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 146

  8   Illuminate\Database\Migrations\Migrator::runPending([])
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Migrations/Migrator.php : 95

  9   Illuminate\Database\Migrations\Migrator::run([])
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Database/Console/Migrations/MigrateCommand.php : 70

  10  Illuminate\Database\Console\Migrations\MigrateCommand::handle()
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  11  call_user_func_array([])
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 29

  12  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 87

  13  Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Object(Closure))
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php : 31

  14  Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), [])
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Container/Container.php : 564

  15  Illuminate\Container\Container::call()
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Console/Command.php : 183

  16  Illuminate\Console\Command::execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/laradmin/vendor/symfony/console/Command/Command.php : 252

  17  Symfony\Component\Console\Command\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Console/Command.php : 170

  18  Illuminate\Console\Command::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/laradmin/vendor/symfony/console/Application.php : 865

  19  Symfony\Component\Console\Application::doRunCommand(Object(Illuminate\Database\Console\Migrations\MigrateCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/laradmin/vendor/symfony/console/Application.php : 241

  20  Symfony\Component\Console\Application::doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/laradmin/vendor/symfony/console/Application.php : 143

  21  Symfony\Component\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Console/Application.php : 88

  22  Illuminate\Console\Application::run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
      /var/www/laradmin/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php : 121

  23  Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

**Comment by jazadev** [comment]
Update with:

use Traits\LarabackUser;
use Traits\Timezone;

The problem persist.

**Comment by jazadev** [comment]
That works for me, thanks!!!
:thumbsup:
