### ISSUE TITLE
Migration Exception

### ISSUE THREAD

**Issue by TheHiddenHaku** [kjdion84/laraback#2]
Laravel: 5.6.11

when i run php artisan migrate i get this error
`Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1364 Field 'timezone' doesn't have a default value (SQL: insert into 'users' ('name', 'email', 'password', 'updated_at', 'created_at') values (Admin, admin@example.com, $2y$10$TIuYHHbdOLmCsKbsMDxnZualSfstmLGbpmY6576m3KFygne.nQBI., 2018-03-10 13:27:26, 2018-03-10 13:27:26))

  at /Users/Alessio/Repo/unio/vendor/laravel/framework/src/Illuminate/Database/Connection.php: 664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   PDOException::("SQLSTATE[HY000]: General error: 1364 Field 'timezone' doesn't have a default value")
      /Users/Alessio/Repo/unio/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 458

  2   PDOStatement::execute()
      /Users/Alessio/Repo/unio/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 458

  Please use the argument -v to see more details.`

**Comment by kjdion84** [comment]
You need to add `timezone` to your `App\User` `$fillables` array.

**Comment by kjdion84** [comment]
Please read the install instructions very carefully. I'll update them later to make it more clear.
